USE [master]
GO

/****** Object:  Database [GM]    Script Date: 07/04/2023 13:00:09 ******/
CREATE DATABASE [GM]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'GM', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\GM.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'GM_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\GM_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [GM].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [GM] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [GM] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [GM] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [GM] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [GM] SET ARITHABORT OFF 
GO

ALTER DATABASE [GM] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [GM] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [GM] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [GM] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [GM] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [GM] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [GM] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [GM] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [GM] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [GM] SET  DISABLE_BROKER 
GO

ALTER DATABASE [GM] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [GM] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [GM] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [GM] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [GM] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [GM] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [GM] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [GM] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [GM] SET  MULTI_USER 
GO

ALTER DATABASE [GM] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [GM] SET DB_CHAINING OFF 
GO

ALTER DATABASE [GM] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [GM] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [GM] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [GM] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [GM] SET QUERY_STORE = OFF
GO

ALTER DATABASE [GM] SET  READ_WRITE 
GO

